version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rzd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

  backend:
    build:
      context: ./rzd-back
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rzd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1

  frontend:
    build:
      context: ./rzd-front-v2.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

  
